DROP SEQUENCE IF EXISTS osoby_seq;

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS osoby CASCADE;
DROP TABLE IF EXISTS jednostki_organizacyjne CASCADE;
DROP TABLE IF EXISTS typy_jednostek CASCADE;
DROP TABLE IF EXISTS przedmioty CASCADE;
DROP TABLE IF EXISTS osoby_na_przedmiotach CASCADE;
DROP TABLE IF EXISTS archiwa CASCADE;
DROP TABLE IF EXISTS wersje_archiwow CASCADE;
DROP TABLE IF EXISTS foldery CASCADE;
DROP TABLE IF EXISTS pliki CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS role_osob CASCADE;
